# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_service_pb2 as chat__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatbotServiceStub(object):
    """*
    챗봇 서비스 정의

    [RPC 메서드]
    - QueryChatbot: 단일 질의-응답 (Unary RPC)

    [향후 확장 가능]
    - StreamChat: 스트리밍 대화 (Server Streaming RPC)
    - BatchQuery: 배치 질의 처리 (Client Streaming RPC)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryChatbot = channel.unary_unary(
                '/com.planit.analytics.grpc.ChatbotService/QueryChatbot',
                request_serializer=chat__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=chat__service__pb2.ChatResponse.FromString,
                _registered_method=True)


class ChatbotServiceServicer(object):
    """*
    챗봇 서비스 정의

    [RPC 메서드]
    - QueryChatbot: 단일 질의-응답 (Unary RPC)

    [향후 확장 가능]
    - StreamChat: 스트리밍 대화 (Server Streaming RPC)
    - BatchQuery: 배치 질의 처리 (Client Streaming RPC)
    """

    def QueryChatbot(self, request, context):
        """*
        챗봇 질의 처리 (Unary RPC)

        사용자의 질의를 받아 AWS Bedrock Claude를 통해
        개인화된 답변을 생성하여 반환합니다.

        @param ChatRequest 사용자 질의
        @return ChatResponse AI 생성 답변
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatbotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryChatbot': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryChatbot,
                    request_deserializer=chat__service__pb2.ChatRequest.FromString,
                    response_serializer=chat__service__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.planit.analytics.grpc.ChatbotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.planit.analytics.grpc.ChatbotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatbotService(object):
    """*
    챗봇 서비스 정의

    [RPC 메서드]
    - QueryChatbot: 단일 질의-응답 (Unary RPC)

    [향후 확장 가능]
    - StreamChat: 스트리밍 대화 (Server Streaming RPC)
    - BatchQuery: 배치 질의 처리 (Client Streaming RPC)
    """

    @staticmethod
    def QueryChatbot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.planit.analytics.grpc.ChatbotService/QueryChatbot',
            chat__service__pb2.ChatRequest.SerializeToString,
            chat__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
