# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat_service.proto\x12\x19\x63om.planit.analytics.grpc\"-\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"E\n\x0c\x43hatResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07sources\x18\x02 \x03(\t\x12\x14\n\x0cgenerated_at\x18\x03 \x01(\t2q\n\x0e\x43hatbotService\x12_\n\x0cQueryChatbot\x12&.com.planit.analytics.grpc.ChatRequest\x1a\'.com.planit.analytics.grpc.ChatResponseB2\n\x19\x63om.planit.analytics.grpcB\x10\x43hatServiceProtoP\x01\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.planit.analytics.grpcB\020ChatServiceProtoP\001\220\001\001'
  _globals['_CHATREQUEST']._serialized_start=49
  _globals['_CHATREQUEST']._serialized_end=94
  _globals['_CHATRESPONSE']._serialized_start=96
  _globals['_CHATRESPONSE']._serialized_end=165
  _globals['_CHATBOTSERVICE']._serialized_start=167
  _globals['_CHATBOTSERVICE']._serialized_end=280
_builder.BuildServices(DESCRIPTOR, 'chat_service_pb2', _globals)
# @@protoc_insertion_point(module_scope)
