# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/report_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/report_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/report_service.proto\x12\x06report\"m\n\x15GenerateReportRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0breport_type\x18\x02 \x01(\t\x12\x15\n\rtarget_period\x18\x03 \x01(\t\x12\x17\n\x0fstatistics_data\x18\x04 \x01(\t\"k\n\x16GenerateReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0breport_data\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x14\n\x0cgenerated_at\x18\x04 \x01(\t2`\n\rReportService\x12O\n\x0eGenerateReport\x12\x1d.report.GenerateReportRequest\x1a\x1e.report.GenerateReportResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.report_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREPORTREQUEST']._serialized_start=38
  _globals['_GENERATEREPORTREQUEST']._serialized_end=147
  _globals['_GENERATEREPORTRESPONSE']._serialized_start=149
  _globals['_GENERATEREPORTRESPONSE']._serialized_end=256
  _globals['_REPORTSERVICE']._serialized_start=258
  _globals['_REPORTSERVICE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
